### ISSUE TITLE
VK Admin を composer のライブラリ化して各プラグインからの読み込みも composer からに移行したい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vektor-wp-libraries#112]
* 現状 gulp で各プラグインに複製して、各プラグインそれぞれにコミットしている
* 複製先は gulpfile.js に書いてあるのでそれを見れば使われてるプラグインがわかるはず

- [x] まずは composer のライブラリ化して、何かのプラグインで１つだけやってみる

---

- [x] lightning-g3-pro-unit https://github.com/vektor-inc/lightning-g3-pro-unit/pull/213
- [x] vk-all-in-one-expansion-unit https://github.com/vektor-inc/vk-all-in-one-expansion-unit/pull/958
- [x] vk-blocks-pro https://github.com/vektor-inc/vk-blocks-pro/pull/1647
- [x] vk-block-patterns https://github.com/vektor-inc/vk-block-patterns/pull/185
- [x] vk-link-target-controller https://github.com/vektor-inc/vk-link-target-controller/pull/72
- [x] vk-post-author-display https://github.com/vektor-inc/vk-post-author-display/pull/72
- [ ] vk-legacy-notice https://github.com/vektor-inc/vk-legacy-notice/pull/39
- [x] vk-plugin-beta-tester https://github.com/vektor-inc/vk-plugin-beta-tester/pull/23

**Comment by drill-lancer** [comment]
いきま～す

**Comment by drill-lancer** [comment]
legacy-notice はまだみたいだけど長らく更新していないため一旦 Close
