### ISSUE TITLE
【確認待ち】[ 投稿タイプマネージャー ] 投稿タイプの設定を保存した時に自動的にパーマリンク保存させたい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vektor-wp-libraries#124]
みんなパーマリンクの保存を忘れて「404 になる」の質問が後を絶たないため

**Comment by drill-lancer** [comment]
鍵を握りそうな呪文

```
$wp_rewrite->set_permalink_structure( $permalink_structure );
```

ソース：
https://github.com/WordPress/WordPress/blob/e249e1aa285cee90ac6d0670170ac24d4e36ff12/wp-admin/options-permalink.php
https://github.com/WordPress/WordPress/blob/e249e1aa285cee90ac6d0670170ac24d4e36ff12/wp-includes/class-wp-rewrite.php
