### ISSUE TITLE
【フォーラムより】投稿詳細ページの下にある前の記事・次の記事 のNEWマークが、「Lightning アーカイブページ設定」の「新着表示する日数」を2などの少ない数字に変更しても、この部分は7日後に消えるようになっている

### ISSUE THREAD

**Issue by goutetsuguma** [vektor-inc/vektor-wp-libraries#144]
投稿詳細ページの下にある前の記事・次の記事 のNEWマークが、「Lightning アーカイブページ設定」の「新着表示する日数」を2などの少ない数字に変更しても、この部分は7日後に消えるようになっているようです。

[				'new_date'                   => 7,](https://github.com/vektor-inc/vektor-wp-libraries/blob/ee0735059e1d5e442d2497115cd52abee96159af/vk-components/package/class-vk-component-posts.php#L59)
この辺りでしょうか、、？？違っていたらすみません

【再現手順】

1. テーマはLightning で、【外観】>【カスタマイズ】の「Lightning アーカイブページ設定」>「投稿」を開き、「表示タイプとカラム[ 投稿 ]」の「表示タイプ」を、例えば「カード」にします（ここは Lightning 標準 以外ならなんでもOKです）
2. 次に下の方にある「表示要素 [ 投稿 ]」の「新着表示」にチェックが入っていることを確認して、「新着表示オプション [ 投稿 ]」の「新着表示する日数」を例えば 1 とかにして、「公開」ボタンをクリックします。
3. カスタマイズの画面は閉じます。次に 適当に、1週間以内の公開日の投稿記事を作成します。（今回は「新着表示する日数」を1にしたので1日より後の投稿日にするのかな）
4. 投稿ページに設定してある固定ページを開きます。そうすると投稿一覧には「NEW」マークがないと思います。詳細ページを開くと「3」で作成した詳細ページのタイトル横にはNEWマークが付いていると思います

https://vws.vektor-inc.co.jp/forums/topic/%e6%8a%95%e7%a8%bf%e4%b8%80%e8%a6%a7%ef%bc%88%e8%a1%a8%e7%a4%ba%e3%82%bf%e3%82%a4%e3%83%97%ef%bc%9d%e3%82%ab%e3%83%bc%e3%83%89%ef%bc%89%e3%81%ae%e3%82%b7%e3%83%a3%e3%83%89%e3%82%a6%e9%bb%92%e5%bd%b1

**Comment by kurudrive** [comment]
詳細ページとアーカイブページは別なので、動作としては正常です。
詳細ページの方のNewの表示日数を指定する機能が現状では存在しないだけです。
これは G3 Pro Unit の方で別途健闘します。

**Comment by kurudrive** [comment]
@goutetsuguma 確認ありがとうございます (￣人￣)
