### ISSUE TITLE
[ Widget PR Content ] トップスライドのように背景画像の上に透過の色を指定出来るようにする

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vektor-wp-libraries#4]
一番安定しそうなのは背景画像を指定しているDIVの上にもう一枚DIVを敷いてそこに色をつけて透過させる事だが、効果として同様の事が得られれば他の手法を用いても良い。

**Comment by catherine87** [comment]
【メモ】bg_cover_depth　に「０」が入るとエラーになる。でも一回中断。あとで直す。
