### ISSUE TITLE
CSSをTreeShakingしないけどheadにインラインでだけ読み込む機能を追加したい

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vektor-wp-libraries#52]
https://vws.vektor-inc.co.jp/forums/topic/%E3%83%88%E3%83%83%E3%83%97%E3%83%9A%E3%83%BC%E3%82%B8%E3%82%B9%E3%83%A9%E3%82%A4%E3%83%89%E3%82%B7%E3%83%A7%E3%83%BC%E3%81%AE%E7%9F%A2%E5%8D%B0%E3%81%AE%E8%89%B2%E3%82%92%E5%A4%89%E3%81%88%E3%81%9F-2

https://trello.com/c/hHX0uZD9/2610-%E3%83%88%E3%83%83%E3%83%97%E3%83%9A%E3%83%BC%E3%82%B8%E3%82%B9%E3%83%A9%E3%82%A4%E3%83%89%E3%82%B7%E3%83%A7%E3%83%BC%E3%81%AE%E7%9F%A2%E5%8D%B0%E3%81%AE%E8%89%B2%E3%82%92%E5%A4%89%E3%81%88%E3%81%9F%E3%81%84

- [x] 仕様検討
- [x] ExUnit
- [x] Katawara
- [x] VK Blocks Pro
- [x] Lightning Pro
- [x] Lightning（g3/main）

※近い将来ブロックを各ブロック毎のCSS読み込みに切り替えて、重くならないようにこのインライン出力を使うようにしたい。

**Comment by drill-lancer** [comment]
https://github.com/vektor-inc/vektor-wp-libraries/blob/958acb877e4758f36a268fe475eceb1a059d4549/vk-css-optimize/package/class-css-tree-shaking.php#L144-L158
上記を活用すれば可能です。何かしらの UI 追加しますか？

**Comment by kurudrive** [comment]
@drill-lancer 面倒だからまずは一旦 TreeShaking が有効に指定されてたら発火する感じで良いかと。

**Comment by drill-lancer** [comment]
@kurudrive 
CSS Optimize の本体を置くのっどれでしたっけ？
ExUnit は置くことは知っていますがそれ以外にありましたっけ？

**Comment by kurudrive** [comment]
@drill-lancer 

今は

Katawara
 VK Blocks Pro
 Lightning Pro
 Lightning（g3/main）

に入ってませんでしたっけ？

**Comment by drill-lancer** [comment]
@kurudrive 
VK Block Pro は設定のみ、他（ExUnit を含む）は本体も入ってます。

**Comment by drill-lancer** [comment]
現状の gulp の設定は下記の通り
https://github.com/vektor-inc/vektor-wp-libraries/blob/3e7dc67d28d280497c3a1c6b1f38a849b0870317/gulpfile.js#L201-L215

**Comment by kurudrive** [comment]
@drill-lancer さんはどういう仕様が良いと思いますか？
自分のベストだと思う仕様を提案して、その内容でOKかNGかを聞くようにしてください。

**Comment by drill-lancer** [comment]
@kurudrive 
とりあえず自分なりに実装してみましたのでご確認ください。
Lightning G3：https://github.com/vektor-inc/lightning/pull/607
Lightning Pro：https://github.com/vektor-inc/lightning-pro/pull/88
Katawara：https://github.com/vektor-inc/katawara/pull/123
ExUnit：https://github.com/vektor-inc/vk-all-in-one-expansion-unit
VK Blocks Pro：https://github.com/vektor-inc/vk-blocks-pro/pull/475

**Comment by kurudrive** [comment]
@drill-lancer 
class-css-tree-shaking.php は今どれくらい改変してます？
改変してないなら、元がアップデートした時にそのまま入れ替えるのでそのままで良いのですが、
ある程度カスタマイズしている場合は例えばCSS最小化の部分（ simple_minify ）は tree-shaking とは違う事になってくるので、"tree-shaking.php" の中からは出したいかなーと思いまして。

**Comment by drill-lancer** [comment]
> class-css-tree-shaking.php は今どれくらい改変してます？
まったくいじっていません（ lint は走ってるかもしれません）

**Comment by kurudrive** [comment]
@drill-lancer 
了解でっす。それなら今の感じで良いのではないかなと思います。

**Comment by drill-lancer** [comment]
@kurudrive 
・・・というかいまメインで使ってる関数でも呼び出されているので下手にいじるほうが危ないと思います。
https://github.com/vektor-inc/vektor-wp-libraries/blob/958acb877e4758f36a268fe475eceb1a059d4549/vk-css-optimize/package/class-css-tree-shaking.php#L160-L230

**Comment by kurudrive** [comment]
@drill-lancer 

class-vk-css-optimize.php の カスタマイズの中で

new Custom_Html_Control(

を呼び出しているけれども、このクラスがあるものとないモノがあると思われる。
※ Lightning は VK_Custom_Html_Control になっている。

なので、事故らないように VK_Custom_Text_Control に書き換えつつ、

`if ( ! class_exist('VK_Custom_Text_Control') ){`

を vk-css-optimize の中で定義しておいた方が良いと思いますがどうでしょう？

**Comment by kurudrive** [comment]
※過去に何度かこのあたりの独自クラスが無いという事でエラー報告を受けているため

**Comment by drill-lancer** [comment]
@kurudrive 
VK_Custom_Text_Control が含まれるファイルってライブラリ化しないのですか？

**Comment by drill-lancer** [comment]
@kurudrive 
今度は逆に下記で事故りそうな気がします。
・Katawara
・ExUnit
・VK Blocks Pro
個人的にはサニタイズ関数や独自実装クラスはライブラリ化したほうが間違いがなさそうなのでそうしたいです。

**Comment by drill-lancer** [comment]
・・・というわけで Issue 立てておきました。
https://github.com/vektor-inc/vektor-wp-libraries/issues/53

**Comment by kurudrive** [comment]
@drill-lancer あー、じゃあ、G3の class-vk-helpers.php を共通管理しましょう。

**Comment by kurudrive** [comment]
でも VK_Custom_Text_Control ってそれ自体が classだから別のやり方になるのか。

**Comment by drill-lancer** [comment]
vk-helpers
トVK Helpers
トVK_Custom_Text_Control

という構築でいいのでは？

**Comment by kurudrive** [comment]
@drill-lancer ですね。
