### ISSUE TITLE
[ 再調整待ち ] ExUnitの管理画面、右サイドのバナー画像にVK Filter Search PRO も設置するのどうでしょう

### ISSUE THREAD

**Issue by drill-lancer** [vektor-inc/vektor-wp-libraries#59]

**Comment by kurudrive** [comment]
- [ ] スキンのバナーは全削除
- [ ] Lightning Pro も削除
- [ ] JobPosting Manager 削除
- [ ] 追加 Filter Search
- [ ] 追加 G3 Pro Unit

**Comment by miminari** [comment]
https://github.com/vektor-inc/vektor-wp-libraries/issues/60#issuecomment-844569905
に関連しますが、こっちだけ先に処理してしまって、↑はゆっくり進めるので良いかなあと思うので、さくっと差し替えてもらってもいい気がします！　@drill-lancer さんなどお手隙の際にいかがでしょう？

**Comment by drill-lancer** [comment]
@kurudrive @miminari @ChiakiKouno 
今 https://github.com/vektor-inc/vektor-wp-libraries/issues/60 をしやすくするための構造変更をしています。
（ vk-admin-banner.php を作成してそこに製品の配列を格納する感じ）

公式ディレクトリのプラグインは商品詳細ページに誘導せず
速攻インストールさせようとしていますが現状ママでいきますか？
（個人的には詳細ページに誘導させるのもありだと思いますが・・・）

（マーケティングに関わる案件なので３人にメンションしておきました。）

**Comment by miminari** [comment]
@drill-lancer 早速ありがとうございますー！
これは、プラグインのバナーを押した時のリンク先という意味ですかね？
私的にはいきなりインストールはちょっとUX的に不味い気がするので公式ディレクトリのページに飛ばして良い気がします。

**Comment by miminari** [comment]
MTGの結果のメモ
- リンク先はプラグインの検索結果なので、現状の仕様のままで良い
- バナーのサイズが違うので改修したい

**Comment by drill-lancer** [comment]
バナー作成待ち
バナーができたら下記ブランチに追加
https://github.com/vektor-inc/vk-banners

**Comment by kurudrive** [comment]
バナーサイズ決定・バナー作成待ち

**Comment by kurudrive** [comment]
https://github.com/vektor-inc/vws-vektor-inc/issues/3

**Comment by kurudrive** [comment]
※「フォーマット決めましょう」はイキですが、急ぎのため一旦作成・掲載して、後から再度フォーマット揃える想定。

**Comment by kurudrive** [comment]
メモ : 右下の VK のロゴはダッシュボードで小さくかすれた感じになってしまうので割合的にもう少し大きくしたい
