### ISSUE TITLE
[ Widget PR Content ][ 最後 ] Origin Pro 以外のスキンにも展開・確認・調整

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vektor-wp-libraries#6]

**Comment by catherine87** [comment]
@kurudrive 

SP表示時など確認して修正したものを
jpnstyle
fort
pale
に展開しました。

origin/pr-content　ブランチでプッシュしてあります。
確認お願いします。

paleについては久納さんとも相談したのですが、全幅でいくか、枠内で収めるか石川さんはどちらを想定していましたか？？
他のスキンも共通ですが、このウィジェットは１カラムのときのみ正常に動作するようにしか整えていないので、もし２カラムのときも使用想定であれば、改めて修正します。
