### ISSUE TITLE
ダッシュボードのお知らせを外部ファイルの読み込みに変更 実装

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vektor-wp-libraries#60]
■ データ項目 
* 画像URL
* 表示するサイトの言語
* リンク先
* alt てきな テキスト
* プラグインかテーマか
* 該当のプラグインorテーマのスラッグ

jsonとか画像は GitHub に置いておく

**Comment by miminari** [comment]
今の処やれる人が進めよう、という話なので、可能性のありそうな人を全員アサインしておきます。
