### ISSUE TITLE
【バナーガイドライン決定後作成】Lightning Copyright Customizer のバーナーはないのですか？

### ISSUE THREAD

**Issue by drill-lancer** [vektor-inc/vektor-wp-libraries#61]

**Comment by kurudrive** [comment]
これは 

* Copyright customizer は売ろうと思って売ってる商品じゃない（非表示のしかた教えて下さいという問い合わせの弾除け）。
* Pro packが有効だったり、特定のテーマが有効だったら非表示などイレギュラーな処理になるよ。

という事を踏まえると、よっぽどウルトラ暇な場合は作れるけど現状のしごと状況からして優先度が極めて低いのでなくてよいかなと思います。

と、思ったけど、WooCommerceの商品画像はどのみち必要なのか...。

**Comment by kurudrive** [comment]
↓ こっちに移動 close
https://github.com/vektor-inc/lightning-pro-child-vws/issues/26

**Comment by kurudrive** [comment]
G３Pro Pack 買ってね
