### ISSUE TITLE
【確認待ち】[ Media Posts BS4 ] 言語ファイルをライブラリ内に独自に持つ

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vektor-wp-libraries#64]
package の中に po ファイルをもたせる
ライブラリphpファイル内でテキストドメインを指定

これによって以下が解消される

* 利用側でテキストドメインの置換処理が不要になる
* 同じ翻訳を展開先で都度行わなくて良い

Lightning は複数のテキストドメインが入ってるとテーマチェック通らないのでLightningに展開するものは使用しない

たぶん Plugin Update Checker がこういう処理やってるはず。

**Comment by drill-lancer** [comment]
実装しましたので確認お願いします。

---

【変更点】
[ Media Posts BS4 ] 言語ファイルをライブラリ内に独自に持つように変更しました。

---

【確認手順・確認事項】

1. gulp copy_media-posts-bs4 を実行
2. 〇〇アーカイブ設定 や 〇〇 Media Posts BS4 ウィジェットに翻訳が反映されているのを確認
