### ISSUE TITLE
[ Widget PR Content ] 文字色を変更出来るように

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vektor-wp-libraries#7]
背景が写真になると読みにくくなるため

**Comment by catherine87** [comment]
@kurudrive 

タイトルとテキスト<p>でそれぞれカラーピッカーを用意しても大丈夫ですか？
たとえば、背景が白でテキストは見やすい場合でも、「デザイン的にタイトルだけ色を変える」という使い方も私ならするかな？と思ったのでー。

**Comment by kurudrive** [comment]
@catherine87 うむうむ、自分で仕様を考えるのは素晴らしいデス。

title:
color_picker:
text:
color_picker:

の方がわかりやすいと思いますよ（・ｗ・ｂ
