### ISSUE TITLE
class-vk-admin.php の最後の行は明らかに不要

### ISSUE THREAD

**Issue by mthaichi** [vektor-inc/vektor-wp-libraries#79]
class-vk-admin.phpの最後の行は不要かと思います。
``` 
Vk_Admin::init();
$Vk_Admin = new Vk_Admin();   // ←これ
```
classのメソッドが全部 static になっているので、コンストラクタを呼び出す意味がないかと思います。
前の行の Vk_Admin::init(); で全部読み込まれると思います。

メモリの節約になるかと思いますし、多分問題ないはずですが、誰かタイミングの良い時に動作確認含めてやってみてください。

**Comment by kurudrive** [comment]
対応済み close
