### ISSUE TITLE
VK Mobile Fix Nav

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vektor-wp-libraries#8]
拡張スキンをはじめ別テーマやフルカスタムのサイトなどにも使用していく基幹ナビゲーション。

メニューボタンをタップして展開する VK Mobile Nav と違って、こちらは主にページ下部に固定表示するタイプ。
形状としては https://snow-monkey.2inc.org/ のようなナビゲーション

毎度の事ではあるが専用ブランチにて開発する。

/vk-mobile-nav/package/class-vk-mobile-fix-nav.php
を新規作成しコードを書いていく。
とりあえず最初は
/vk-mobile-nav/vk-mobile-nav-config.php
から class-vk-mobile-fix-nav.php を読み込む

当然ここに書いただけでは動作確認が出来ないので、

```
$ gulp watch_mobile
```

を走らせながら作業する

## 入力欄について

カスタマイザーで VK Mobile Fix Nav パネルを追加

入力させるアイテムは以下の通り

* テキスト
* アイコン
* リンク先
* ターゲット

ボタンは４つを想定。つまり入力欄は４セットになるので、foreachなどでループして書く。

これとは別で、全体として

* 文字の色
* 背景の色

を設定・反映出来るようにする

## HTMLの出力について

HTMLはとりあえず wp_footer に出力されるようにする。
CSS についてはとりあえず

/vk-mobile-nav/package/_scss/_fix-nav.scss

を新規追加してそこに書くいて、

/vk-mobile-nav/package/_scss/vk-mobile-nav-bright.scss

でインポートする

**Comment by catherine87** [comment]
@kurudrive 

ページカレントですが
テキストやアイコンの色が任意のカラーが入ってくるので、
pr-content-widget と同様に一定の数値以上なら #000 それ以下なら #fff かとの指定でいいですか？

**Comment by kurudrive** [comment]
背景未指定の場合は #fff の方が良いかなと（・ｗ・

**Comment by catherine87** [comment]
@kurudrive 

はい。
では設定がない場合は #fff に変更します。
が、カレントの処理はどうしますか？？

**Comment by kurudrive** [comment]
背景未指定 : 白
文字未指定 : 指定なし（ body の color 適用 ）

んー、これ条件分岐とか考えても人によって好みわかれるから、
hover時用の色設定も追加した方がいいかもしれないね。

例えば背景白だとしてカレント時に色反転したい人も居れば文字色だけ変更したい人もいるだろうし。

**Comment by catherine87** [comment]
@kurudrive 

スマホの時に hover ってどんな反応？表示になりますか？
あまりスマホの時に hover って意識したことなかったのですが。

**Comment by kurudrive** [comment]
@catherine87 hoverはないっす（・ｗ・

**Comment by catherine87** [comment]
@kurudrive 

「hover時用の色設定も追加した方がいいかもしれないね。」
=>これはカラーピッカー追加で設定できるようにした方がいいという意味ではないってことですか？

**Comment by kurudrive** [comment]
あぁ、ごめん、hoverっていうかカレント（アクティブ）表示ね。
そうそう、カラーピッカーを追加しちゃうっていう意味です。

**Comment by catherine87** [comment]
@kurudrive 

CSS は直書きの状態ですけど、page-current の動きはできたかなーって感じです。
page-current のカラーピッカーの値がからの場合は何色を設定しますか？
