### ISSUE TITLE
[ vk-posts ] 見出しのタグをフックで変更できるようにする。postのパラメーターに追加。

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vektor-wp-libraries#90]
https://vws.vektor-inc.co.jp/forums/topic/%e6%8a%95%e7%a8%bf%e3%83%aa%e3%82%b9%e3%83%88%e3%81%ae%e8%a6%8b%e5%87%ba%e3%81%97%e3%82%92h5%e3%81%8b%e3%82%89h3%e3%81%ab%e3%81%97%e3%81%9f%e3%81%84

**Comment by drill-lancer** [comment]
@kurudrive 
これって `h5` をフィルターフックの対象にするのか、
`<h5 class="vk_post_title ' . $layout_type . '-title">` と `</h5>` をフィルターフックの対象にするのかが
わかっていないのですが石川さん的には前者を想定していますでしょうか？

**Comment by kurudrive** [comment]
前者を vk_posts のプションで指定できればいいかなと。

**Comment by drill-lancer** [comment]
@kurudrive 
了解しました。そのように致します。
