### ISSUE TITLE
Tree shaking が効いてない空気を感じるので確認よろしくお願いいたします。

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vektor-wp-libraries#93]
https://demo.dev3.biz/lightning-g3/wp-admin/customize.php?url=https%3A%2F%2Fdemo.dev3.biz%2Flightning-g3%2F
view-source:https://demo.dev3.biz/lightning-g3/

プライベートサポート関連

**Comment by kurudrive** [comment]
@drill-lancer これ最優先で確認よろしくお願いいたします。

**Comment by drill-lancer** [comment]
Composer での実装になったので一旦 Close
